import { StyleSheet, Platform, Dimensions } from 'react-native';

const styles = StyleSheet.create({
  bgTransparent: { backgroundColor: 'transparent' },
  bgBlack: { backgroundColor: '#212529' },
  bgGreyDarkest: { backgroundColor: '#3d4852' },
  bgGreyDarker: { backgroundColor: '#606f7b' },
  bgGreyDark: { backgroundColor: '#8795a1' },
  bgGrey: { backgroundColor: '#b8c2cc' },
  bgGreyLight: { backgroundColor: '#dae1e7' },
  bgGreyLighter: { backgroundColor: '#f1f5f8' },
  bgGreyLightest: { backgroundColor: '#f8fafc' },
  bgWhite: { backgroundColor: '#fff' },
  borderTransparent: { borderColor: 'transparent' },
  borderBlack: { borderColor: '#22292f' },
  borderGreyDarkest: { borderColor: '#3d4852' },
  borderGreyDarker: { borderColor: '#606f7b' },
  borderGreyDark: { borderColor: '#8795a1' },
  borderGrey: { borderColor: '#b8c2cc' },
  borderGreyLight: { borderColor: '#dae1e7' },
  borderGreyLighter: { borderColor: '#f1f5f8' },
  borderGreyLightest: { borderColor: '#f8fafc' },
  borderWhite: { borderColor: '#fff' },
  roundedNone: { borderRadius: 0 },
  roundedSm: { borderRadius: 2 },
  rounded: { borderRadius: 4 },
  roundedLg: { borderRadius: 8 },
  roundedFull: { borderRadius: 9999 },
  roundedTNone: { borderTopLeftRadius: 0, borderTopRightRadius: 0 },
  roundedRNone: { borderTopRightRadius: 0, borderBottomRightRadius: 0 },
  roundedBNone: { borderBottomRightRadius: 0, borderBottomLeftRadius: 0 },
  roundedLNone: { borderTopLeftRadius: 0, borderBottomLeftRadius: 0 },
  roundedTSm: { borderTopLeftRadius: 2, borderTopRightRadius: 2 },
  roundedRSm: { borderTopRightRadius: 2, borderBottomRightRadius: 2 },
  roundedBSm: { borderBottomRightRadius: 2, borderBottomLeftRadius: 2 },
  roundedLSm: { borderTopLeftRadius: 2, borderBottomLeftRadius: 2 },
  roundedT: { borderTopLeftRadius: 4, borderTopRightRadius: 4 },
  roundedR: { borderTopRightRadius: 4, borderBottomRightRadius: 4 },
  roundedB: { borderBottomRightRadius: 4, borderBottomLeftRadius: 4 },
  roundedL: { borderTopLeftRadius: 4, borderBottomLeftRadius: 4 },
  roundedTLg: { borderTopLeftRadius: 8, borderTopRightRadius: 8 },
  roundedRLg: { borderTopRightRadius: 8, borderBottomRightRadius: 8 },
  roundedBLg: { borderBottomRightRadius: 8, borderBottomLeftRadius: 8 },
  roundedLLg: { borderTopLeftRadius: 8, borderBottomLeftRadius: 8 },
  roundedTFull: { borderTopLeftRadius: 9999, borderTopRightRadius: 9999 },
  roundedRFull: { borderTopRightRadius: 9999, borderBottomRightRadius: 9999 },
  roundedBFull: { borderBottomRightRadius: 9999, borderBottomLeftRadius: 9999 },
  roundedLFull: { borderTopLeftRadius: 9999, borderBottomLeftRadius: 9999 },
  roundedTlNone: { borderTopLeftRadius: 0 },
  roundedTrNone: { borderTopRightRadius: 0 },
  roundedBrNone: { borderBottomRightRadius: 0 },
  roundedBlNone: { borderBottomLeftRadius: 0 },
  roundedTlSm: { borderTopLeftRadius: 2 },
  roundedTrSm: { borderTopRightRadius: 2 },
  roundedBrSm: { borderBottomRightRadius: 2 },
  roundedBlSm: { borderBottomLeftRadius: 2 },
  roundedTl: { borderTopLeftRadius: 4 },
  roundedTr: { borderTopRightRadius: 4 },
  roundedBr: { borderBottomRightRadius: 4 },
  roundedBl: { borderBottomLeftRadius: 4 },
  roundedTlLg: { borderTopLeftRadius: 8 },
  roundedTrLg: { borderTopRightRadius: 8 },
  roundedBrLg: { borderBottomRightRadius: 8 },
  roundedBlLg: { borderBottomLeftRadius: 8 },
  roundedTlFull: { borderTopLeftRadius: 9999 },
  roundedTrFull: { borderTopRightRadius: 9999 },
  roundedBrFull: { borderBottomRightRadius: 9999 },
  roundedBlFull: { borderBottomLeftRadius: 9999 },
  borderSolid: { borderStyle: 'solid' },
  borderDashed: { borderStyle: 'dashed' },
  borderDotted: { borderStyle: 'dotted' },
  border0: { borderWidth: 0 },
  border2: { borderWidth: 2 },
  border4: { borderWidth: 4 },
  border8: { borderWidth: 8 },
  border: { borderWidth: 1 },
  borderT0: { borderTopWidth: 0 },
  borderR0: { borderRightWidth: 0 },
  borderB0: { borderBottomWidth: 0 },
  borderL0: { borderLeftWidth: 0 },
  borderT2: { borderTopWidth: 2 },
  borderR2: { borderRightWidth: 2 },
  borderB2: { borderBottomWidth: 2 },
  borderL2: { borderLeftWidth: 2 },
  borderT4: { borderTopWidth: 4 },
  borderR4: { borderRightWidth: 4 },
  borderB4: { borderBottomWidth: 4 },
  borderL4: { borderLeftWidth: 4 },
  borderT8: { borderTopWidth: 8 },
  borderR8: { borderRightWidth: 8 },
  borderB8: { borderBottomWidth: 8 },
  borderL8: { borderLeftWidth: 8 },
  borderT: { borderTopWidth: 1 },
  borderR: { borderRightWidth: 1 },
  borderB: { borderBottomWidth: 1 },
  borderL: { borderLeftWidth: 1 },
  hidden: { display: 'none' },
  flex: { display: 'flex' },
  flexRow: { flexDirection: 'row' },
  flexRowReverse: { flexDirection: 'row-reverse' },
  flexCol: { flexDirection: 'column' },
  flexColReverse: { flexDirection: 'column-reverse' },
  flexWrap: { flexWrap: 'wrap' },
  flexNoWrap: { flexWrap: 'nowrap' },
  itemsStart: { alignItems: 'flex-start' },
  itemsEnd: { alignItems: 'flex-end' },
  itemsCenter: { alignItems: 'center' },
  itemsBaseline: { alignItems: 'baseline' },
  itemsStretch: { alignItems: 'stretch' },
  selfAuto: { alignSelf: 'auto' },
  selfStart: { alignSelf: 'flex-start' },
  selfEnd: { alignSelf: 'flex-end' },
  selfCenter: { alignSelf: 'center' },
  selfStretch: { alignSelf: 'stretch' },
  justifyStart: { justifyContent: 'flex-start' },
  justifyEnd: { justifyContent: 'flex-end' },
  justifyCenter: { justifyContent: 'center' },
  justifyBetween: { justifyContent: 'space-between' },
  justifyAround: { justifyContent: 'space-around' },
  contentCenter: { alignContent: 'center' },
  contentStart: { alignContent: 'flex-start' },
  contentEnd: { alignContent: 'flex-end' },
  contentBetween: { alignContent: 'space-between' },
  contentAround: { alignContent: 'space-around' },
  flex1: { flex: 1 },
  flex2: { flex: 2 },
  flex3: { flex: 3 },
  flex4: { flex: 4 },
  flex5: { flex: 5 },
  fontHairline: { fontWeight: '100' },
  fontThin: { fontWeight: '200' },
  fontLight: { fontWeight: '300' },
  fontNormal: { fontWeight: '400' },
  fontMedium: { fontWeight: '500' },
  fontSemibold: { fontWeight: '600' },
  fontBold: { fontWeight: '700' },
  fontExtrabold: { fontWeight: '800' },
  fontBlack: { fontWeight: '900' },
  w1: { width: 1 },
  w4: { width: 4 },
  w8: { width: 8 },
  w12: { width: 12 },
  w16: { width: 16 },
  w24: { width: 24 },
  w32: { width: 32 },
  w40: { width: 40 },
  w48: { width: 48 },
  w60: { width: 60 },
  w64: { width: 64 },
  w96: { width: 96 },
  w128: { width: 128 },
  w180: { width: 180 },
  w192: { width: 192 },
  w256: { width: 256 },
  w512: { width: 512 },
  w1_2: { width: '50%' },
  w1_3: { width: '33.33333%' },
  w2_3: { width: '66.66667%' },
  w1_4: { width: '25%' },
  w3_4: { width: '75%' },
  w1_5: { width: '20%' },
  w2_5: { width: '40%' },
  w3_5: { width: '60%' },
  w4_5: { width: '80%' },
  w1_6: { width: '16.66667%' },
  w5_6: { width: '83.33333%' },
  wFull: { width: '100%' },
  wScreen: { width: Dimensions.get('window').width },
  h1: { height: 1 },
  h4: { height: 4 },
  h8: { height: 8 },
  h12: { height: 12 },
  h16: { height: 16 },
  h24: { height: 24 },
  h32: { height: 32 },
  h40: { height: 40 },
  h48: { height: 48 },
  h60: { height: 60 },
  h64: { height: 64 },
  h96: { height: 96 },
  h128: { height: 128 },
  h180: { height: 180 },
  h192: { height: 192 },
  h256: { height: 256 },
  h512: { height: 512 },
  h1_2: { height: '50%' },
  h1_3: { height: '33.33333%' },
  h2_3: { height: '66.66667%' },
  h1_4: { height: '25%' },
  h3_4: { height: '75%' },
  h1_5: { height: '20%' },
  h2_5: { height: '40%' },
  h3_5: { height: '60%' },
  h4_5: { height: '80%' },
  h1_6: { height: '16.66667%' },
  h5_6: { height: '83.33333%' },
  hFull: { height: '100%' },
  hScreen: { height: Dimensions.get('window').height },

  m0: { marginTop: 0, marginBottom: 0, marginRight: 0, marginLeft: 0 },
  m1: { marginTop: 4, marginBottom: 4, marginRight: 4, marginLeft: 4 },
  m2: { marginTop: 8, marginBottom: 8, marginRight: 8, marginLeft: 8 },
  m3: { marginTop: 12, marginBottom: 12, marginRight: 12, marginLeft: 12 },
  m4: { marginTop: 16, marginBottom: 16, marginRight: 16, marginLeft: 16 },
  m6: { marginTop: 24, marginBottom: 24, marginRight: 24, marginLeft: 24 },
  m8: { marginTop: 32, marginBottom: 32, marginRight: 32, marginLeft: 32 },
  mAuto: {
    marginTop: 'auto',
    marginBottom: 'auto',
    marginRight: 'auto',
    marginLeft: 'auto',
  },
  mpx: { marginTop: 1, marginBottom: 1, marginRight: 1, marginLeft: 1 },
  my0: { marginTop: 0, marginBottom: 0 },
  mx0: { marginLeft: 0, marginRight: 0 },
  my1: { marginTop: 4, marginBottom: 4 },
  mx1: { marginLeft: 4, marginRight: 4 },
  my2: { marginTop: 8, marginBottom: 8 },
  mx2: { marginLeft: 8, marginRight: 8 },
  my3: { marginTop: 12, marginBottom: 12 },
  mx3: { marginLeft: 12, marginRight: 12 },
  my4: { marginTop: 16, marginBottom: 16 },
  mx4: { marginLeft: 16, marginRight: 16 },
  my6: { marginTop: 24, marginBottom: 24 },
  mx6: { marginLeft: 24, marginRight: 24 },
  my8: { marginTop: 32, marginBottom: 32 },
  mx8: { marginLeft: 32, marginRight: 32 },
  myAuto: { marginTop: 'auto', marginBottom: 'auto' },
  mxAuto: { marginLeft: 'auto', marginRight: 'auto' },
  mypx: { marginTop: 1, marginBottom: 1 },
  mxpx: { marginLeft: 1, marginRight: 1 },
  mt0: { marginTop: 0 },
  mr0: { marginRight: 0 },
  mb0: { marginBottom: 0 },
  ml0: { marginLeft: 0 },
  mt1: { marginTop: 4 },
  mr1: { marginRight: 4 },
  mb1: { marginBottom: 4 },
  ml1: { marginLeft: 4 },
  mt2: { marginTop: 8 },
  mr2: { marginRight: 8 },
  mb2: { marginBottom: 8 },
  ml2: { marginLeft: 8 },
  mt3: { marginTop: 12 },
  mr3: { marginRight: 12 },
  mb3: { marginBottom: 12 },
  ml3: { marginLeft: 12 },
  mt4: { marginTop: 16 },
  mr4: { marginRight: 16 },
  mb4: { marginBottom: 16 },
  ml4: { marginLeft: 16 },
  mt6: { marginTop: 24 },
  mr6: { marginRight: 24 },
  mb6: { marginBottom: 24 },
  ml6: { marginLeft: 24 },
  mt8: { marginTop: 32 },
  mr8: { marginRight: 32 },
  mb8: { marginBottom: 32 },
  ml8: { marginLeft: 32 },
  mtAuto: { marginTop: 'auto' },
  mrAuto: { marginRight: 'auto' },
  mbAuto: { marginBottom: 'auto' },
  mlAuto: { marginLeft: 'auto' },
  mtpx: { marginTop: 1 },
  mrpx: { marginRight: 1 },
  mbpx: { marginBottom: 1 },
  mlpx: { marginLeft: 1 },
  maxHFull: { maxHeight: '100%' },
  maxWFull: { maxWidth: '100%' },
  minH0: { minHeight: 0 },
  minHFull: { minHeight: '100%' },
  minW0: { minWidth: 0 },
  minWFull: { minWidth: '100%' },
  opacity0: { opacity: 0 },
  opacity25: { opacity: 0.25 },
  opacity50: { opacity: 0.5 },
  opacity75: { opacity: 0.75 },
  opacity100: { opacity: 1 },
  p0: { paddingTop: 0, paddingBottom: 0, paddingRight: 0, paddingLeft: 0 },
  p1: { paddingTop: 4, paddingBottom: 4, paddingRight: 4, paddingLeft: 4 },
  p2: { paddingTop: 8, paddingBottom: 8, paddingRight: 8, paddingLeft: 8 },
  p3: { paddingTop: 12, paddingBottom: 12, paddingRight: 12, paddingLeft: 12 },
  p4: { paddingTop: 16, paddingBottom: 16, paddingRight: 16, paddingLeft: 16 },
  p6: { paddingTop: 24, paddingBottom: 24, paddingRight: 24, paddingLeft: 24 },
  p8: { paddingTop: 32, paddingBottom: 32, paddingRight: 32, paddingLeft: 32 },
  ppx: { paddingTop: 1, paddingBottom: 1, paddingRight: 1, paddingLeft: 1 },
  py0: { paddingTop: 0, paddingBottom: 0 },
  px0: { paddingLeft: 0, paddingRight: 0 },
  py1: { paddingTop: 4, paddingBottom: 4 },
  px1: { paddingLeft: 4, paddingRight: 4 },
  py2: { paddingTop: 8, paddingBottom: 8 },
  px2: { paddingLeft: 8, paddingRight: 8 },
  py3: { paddingTop: 12, paddingBottom: 12 },
  px3: { paddingLeft: 12, paddingRight: 12 },
  py4: { paddingTop: 16, paddingBottom: 16 },
  px4: { paddingLeft: 16, paddingRight: 16 },
  py6: { paddingTop: 24, paddingBottom: 24 },
  px6: { paddingLeft: 24, paddingRight: 24 },
  py8: { paddingTop: 32, paddingBottom: 32 },
  px8: { paddingLeft: 32, paddingRight: 32 },
  pypx: { paddingTop: 1, paddingBottom: 1 },
  pxpx: { paddingLeft: 1, paddingRight: 1 },
  pt0: { paddingTop: 0 },
  pr0: { paddingRight: 0 },
  pb0: { paddingBottom: 0 },
  pl0: { paddingLeft: 0 },
  pt1: { paddingTop: 4 },
  pr1: { paddingRight: 4 },
  pb1: { paddingBottom: 4 },
  pl1: { paddingLeft: 4 },
  pt2: { paddingTop: 8 },
  pr2: { paddingRight: 8 },
  pb2: { paddingBottom: 8 },
  pl2: { paddingLeft: 8 },
  pt3: { paddingTop: 12 },
  pr3: { paddingRight: 12 },
  pb3: { paddingBottom: 12 },
  pl3: { paddingLeft: 12 },
  pt4: { paddingTop: 16 },
  pr4: { paddingRight: 16 },
  pb4: { paddingBottom: 16 },
  pl4: { paddingLeft: 16 },
  pt6: { paddingTop: 24 },
  pr6: { paddingRight: 24 },
  pb6: { paddingBottom: 24 },
  pl6: { paddingLeft: 24 },
  pt8: { paddingTop: 32 },
  pr8: { paddingRight: 32 },
  pb8: { paddingBottom: 32 },
  pl8: { paddingLeft: 32 },
  ptpx: { paddingTop: 1 },
  prpx: { paddingRight: 1 },
  pbpx: { paddingBottom: 1 },
  plpx: { paddingLeft: 1 },
  absolute: { position: 'absolute' },
  relative: { position: 'relative' },
  pinNone: { top: 'auto', right: 'auto', bottom: 'auto', left: 'auto' },
  pin: { top: 0, right: 0, bottom: 0, left: 0 },
  pinY: { top: 0, bottom: 0 },
  pinX: { right: 0, left: 0 },
  pinT: { top: 0 },
  pinR: { right: 0 },
  pinB: { bottom: 0 },
  pinL: { left: 0 },
  textLeft: { textAlign: 'left' },
  textCenter: { textAlign: 'center' },
  textRight: { textAlign: 'right' },
  textJustify: { textAlign: 'justify' },
  textTransparent: { color: 'transparent' },
  textBlack: { color: '#22292f' },
  textGreyDarkest: { color: '#3d4852' },
  textGreyDarker: { color: '#606f7b' },
  textGreyDark: { color: '#8795a1' },
  textGrey: { color: '#b8c2cc' },
  textGreyLight: { color: '#dae1e7' },
  textGreyLighter: { color: '#f1f5f8' },
  textGreyLightest: { color: '#f8fafc' },
  textWhite: { color: '#fff' },
  textXs: { fontSize: 12 },
  textSm: { fontSize: 14 },
  textBase: { fontSize: 16 },
  textLg: { fontSize: 18 },
  textXl: { fontSize: 20 },
  text2xl: { fontSize: 24, lineHeight: 30 },
  text3xl: { fontSize: 30 },
  text4xl: { fontSize: 36, lineHeight: 44 },
  text5xl: { fontSize: 48 },
  italic: { fontStyle: 'italic' },
  roman: { fontStyle: 'normal' },
  trackingTight: { letterSpacing: -0.8 },
  trackingNormal: { letterSpacing: 0 },
  trackingWide: { letterSpacing: 0.8 },
  uppercase: { textTransform: 'uppercase' },
  lowercase: { textTransform: 'lowercase' },
  capitalize: { textTransform: 'capitalize' },
  overlayBlack: { backgroundColor: 'rgba(0, 0, 0, 0.2)' },
  overlayWhite: { backgroundColor: 'rgba(255, 255, 255, 0.2)' },
  shadow: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,

    elevation: 1,
  },
  shadow2: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  shadow3: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
});
